source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target 'steve_mobile' do

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
pod 'react-native-config', :path => '../node_modules/react-native-config'

end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-config'
#       phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
#       phase.shell_script = "cd ../../"\
#                            " && RNC_ROOT=./node_modules/react-native-config/"\
#                            " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
#                            " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
#                            " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

#       target.build_phases << phase
#       target.build_phases.move(phase,0)
#     end
#   end
# end